#!/bin/bash

echo "🔐 NOWPayments Environment Variables for Vercel"
echo "================================================"
echo ""
echo "Please add these environment variables to Vercel manually:"
echo ""
echo "1. NOWPAYMENTS_API_KEY"
echo "   Value: JZ8ZNSN-AZV4J0X-QAWWAH9-3DMRX2X"
echo "   Target: Production, Preview, Development"
echo ""
echo "2. NOWPAYMENTS_IPN_SECRET"
echo "   Value: EG40+dM/v7+s80D5ZJX/k8wqpSnL3/eo"
echo "   Target: Production, Preview, Development"
echo ""
echo "3. NOWPAYMENTS_SANDBOX"
echo "   Value: false"
echo "   Target: Production, Preview, Development"
echo ""
echo "To add via Vercel dashboard:"
echo "1. Go to https://vercel.com/authichain/settings/environment-variables"
echo "2. Add each variable with the values above"
echo "3. Select all environments (Production, Preview, Development)"
echo "4. Click Save"
echo ""
echo "Or use Vercel CLI:"
echo "vercel env add NOWPAYMENTS_API_KEY production"
echo "vercel env add NOWPAYMENTS_IPN_SECRET production"
echo "vercel env add NOWPAYMENTS_SANDBOX production"
